[phases.setup]
nixPkgs = ["php83", "composer", "nodejs"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear"
]
